eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState
  health:
    readinessstate:
      enabled: true