spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book
    username: umut
    password: umut
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

application:
  security:
    jwt:
      secret: githubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidil
      expiration: 8640000