spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/user
    username: umut
    password: umut
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8084

springdoc:
  api-docs:
    path: /user-service/v3/api-docs

application:
  security:
    jwt:
      secret: githubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidilgithubcomumutyenidil
      expiration: 8640000