services:
  postgres:
    container_name: lm_postgres
    image: postgres
    environment:
      POSTGRES_USER: umut
      POSTGRES_PASSWORD: umut
      PGDATA: /var/lib/postgresql/data
    volumes:
      - lm_postgres_data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  zipkin:
    container_name: lm_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - lm_network

networks:
  lm_network:
    driver: bridge

volumes:
  lm_postgres_data: