spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations

server:
  port: 8081

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,readiness
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState
  health:
    readinessstate:
      enabled: true